version: '3.4'

services:
  mfdashboard:
    image: mfdashboard
    build:
      context: dashboard/mf-dashboard
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 4204:4204
